### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by MarcelloTheArcane** [nhost/hasura-backend-plus#187]
I'm coming across an error, which is also creating another error in this error handler, because there is no such thing as `err.output` in this line:

https://github.com/nhost/hasura-backend-plus/blob/dc40aa62e857bde878f79c0a3e71a44f3ff2d0e6/src/index.js#L74

**Comment by elitan** [comment]
This is usually due to the fact that we are not using `Boom` everywhere. 

Do you know what it's causing the error in the first place? What endpoint and where does the code break?

**Comment by MarcelloTheArcane** [comment]
The error is this:

```
TypeError: Cannot read property 'statusCode' of undefined
    at app.use (/app/src/index.js:74:32)
    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/app/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/app/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

I get it from `/storage/upload`, but I'm not completely sure why. I'm using the `X-Hasura-Admin-Secret` and `X-Path` headers, and I have a permissive storage rules function (return true).

**Comment by hawkeye64** [comment]
I fixed this in https://github.com/nhost/hasura-backend-plus/pull/195
