### ISSUE TITLE
Register an email that already exist give back a 500

### ISSUE THREAD

**Issue by SkinyMonkey** [nhost/hasura-backend-plus#207]
Register a new account with an email that already exist give back a 500 instead of a 400

```
POST /auth/local/register/ 500 96 - 118.183 ms
{ Error: Uniqueness violation. duplicate key value violates unique constraint "users_email_key": {"response":{"errors":[{"extensions":{"path":"$.selectionSet.insert_users.args.objects[0]","code":"constraint-violation"},"message":"Uniqueness violation. duplicate key value violates unique constraint \"users_email_key\""}],"status":200},"request":{"query":"\n  mutation (\n    $user: users_insert_input!\n  ) {\n    insert_users (\n      objects: [$user]\n    ) {\n      affected_rows\n    }\n  }\n  ","variables":{"user":{"display_name":"test2","email":"test2@crates.com","active":false,"secret_token":"93764fab-769f-4b7c-97f0-9606c6155f53","user_accounts":{"data":{"username":"test2","email":"test2@crates.com","password":"$2a$10$Rtrj/JlNaQKo75B1/trvFuoJ0l.8jdLqxEfjIXzkE3uX96HN6nq8O"}}}}}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/src/index.js:116:35)
    at step (/app/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/app/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/app/node_modules/graphql-request/dist/src/index.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response: { errors: [ [Object] ], status: 200 },
  request:
   { query:
      '\n  mutation (\n    $user: users_insert_input!\n  ) {\n    insert_users (\n      objects: [$user]\n    ) {\n      affected_rows\n    }\n  }\n  ',
     variables: { user: [Object] } } }
Unable to create user.
Error: Unable to create user.
    at router.post (/app/src/auth/local.js:76:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by plmercereau** [comment]
Hello @SkinyMonkey, 
I'm not sure @elitan will have to fix this on HBP v1 as we are about to release v2. But this bug won't occur on v2 hopefully!

**Comment by elitan** [comment]
I think we should create a v1 branch with bugfixes like this. And label issues related to v1 with v1.
