### ISSUE TITLE
Storage TimeoutError Causing Crash

### ISSUE THREAD

**Issue by aaronhayes** [nhost/hasura-backend-plus#324]
I'm getting an occasional timeout error when requesting objects from s3. I'm not sure how to replicate this consistently other than just retrying.

This needs to be handled gracefully as it actually crashes the server, and I'm seeing it fairly regularly now 

p.s. I saw this before I added the streaming 😄  but thought it might have been a one-off and didn't capture the error.

```
Error [TimeoutError]: Connection timed out after 120000ms
    at ClientRequest.<anonymous> (/app/node_modules/aws-sdk/lib/http/node.js:86:34)
    at Object.onceWrapper (events.js:420:28)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.emitRequestTimeout (_http_client.js:769:9)
    at Object.onceWrapper (events.js:420:28)
    at TLSSocket.emit (events.js:326:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7) {
  code: 'TimeoutError',
  time: 2020-08-27T08:04:29.196Z,
  region: 'ap-southeast-2',
  hostname: 's3.ap-southeast-2.amazonaws.com',
  retryable: false,
  statusCode: 200,
  retryDelay: 15.138183331924736
}
/app/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Internal Server Error
    at PassThrough.<anonymous> (/app/dist/routes/storage/get.js:44:34)
    at PassThrough.emit (events.js:326:22)
    at PassThrough.EventEmitter.emit (domain.js:486:12)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:587:14)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/app/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at Request.RESET_RETRY_STATE (/app/node_modules/aws-sdk/lib/event_listeners.js:481:9)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:102:18) {
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  },
  isDeveloperError: true,
  code: 'Error',
  time: 2020-08-27T08:04:29.197Z
}
```

**Comment by aaronhayes** [comment]
ooh this might have been fixed in `2.2.0`. I thought I was running the latest version but wasn't! 

Will close and keep watch incase it reoccurs.
