### ISSUE TITLE
Logout from nhost-js-sdk throws an error

### ISSUE THREAD

**Issue by SkinyMonkey** [nhost/hasura-backend-plus#355]
```
Error: expecting a value for non-nullable variable: refresh_token of type: uuid! in variableValues: {"response":{"errors":[{"extensions":{"path":"$.variableValues","code":"validation-failed"},"message":"expecting a value for non-nullable variable: refresh_token of type: uuid! in variableValues"}],"status":200},"request":{"query":"mutation ($refresh_token: uuid!) {\n  delete_auth_refresh_tokens(where: {refresh_token: {_eq: $refresh_token}}) {\n    affected_rows\n  }\n}\n","variables":{}}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/src/index.js:116:35)
    at step (/app/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/app/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/app/node_modules/graphql-request/dist/src/index.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: { errors: [ [Object] ], status: 200 },
  request: {
    query: 'mutation ($refresh_token: uuid!) {\n' +
      '  delete_auth_refresh_tokens(where: {refresh_token: {_eq: $refresh_token}}) {\n' +
      '    affected_rows\n' +
      '  }\n' +
      '}\n',
    variables: { refresh_token: undefined }
  }
}```

**Comment by SkinyMonkey** [comment]
It seems like nhost-js-sdk is sendint the refresh token as a query parameter called refresh_token.
Is it the library that is not up to date?
In HBP+ i can see that the refresh_token is extracted from the cookies, which are btw optional if i remember well?
