### ISSUE TITLE
Register from nhos-js-sdk throws an error

### ISSUE THREAD

**Issue by SkinyMonkey** [nhost/hasura-backend-plus#357]
```OPTIONS /auth/register 204 0 - 0.260 ms
Error: expecting a value for non-nullable variable: ticket of type: uuid! in variableValues: {"response":{"errors":[{"extensions":{"path":"$.variableValues","code":"validation-failed"},"message":"expecting a value for non-nullable variable: ticket of type: uuid! in variableValues"}],"status":200},"request":{"query":"query ($ticket: uuid!) {\n  auth_accounts(where: {ticket: {_eq: $ticket}}) {\n    ...accountFragment\n  }\n}\n\nfragment accountFragment on auth_accounts {\n  id\n  active\n  default_role\n  account_roles {\n    role\n  }\n  user {\n    id\n    display_name\n  }\n  is_anonymous\n  ticket\n  email\n  new_email\n  otp_secret\n  mfa_enabled\n  password_hash\n}\n","variables":{}}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/src/index.js:116:35)
    at step (/app/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/app/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/app/node_modules/graphql-request/dist/src/index.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: { errors: [ [Object] ], status: 200 },
  request: {
    query: 'query ($ticket: uuid!) {\n' +
      '  auth_accounts(where: {ticket: {_eq: $ticket}}) {\n' +
      '    ...accountFragment\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment accountFragment on auth_accounts {\n' +
      '  id\n' +
      '  active\n' +
      '  default_role\n' +
      '  account_roles {\n' +
      '    role\n' +
      '  }\n' +
      '  user {\n' +
      '    id\n' +
      '    display_name\n' +
      '  }\n' +
      '  is_anonymous\n' +
      '  ticket\n' +
      '  email\n' +
      '  new_email\n' +
      '  otp_secret\n' +
      '  mfa_enabled\n' +
      '  password_hash\n' +
      '}\n',
    variables: { ticket: undefined }
  }
}
POST /auth/register 204 - - 183.515 ms```

**Comment by MichaelJCole** [comment]
I had to apply this patch for HBP work for me.
