### ISSUE TITLE
Facebook provider throws an error after accepting the app permissions on facebook

### ISSUE THREAD

**Issue by SkinyMonkey** [nhost/hasura-backend-plus#358]
After accepting the use of my data by my app, i was redirected to this path:

localhost:3000/auth/providers/facebook/callback?code=<THE AUTH CODE RETURNED BY FACEBOOK>

# Logs:
```
GET /auth/providers/facebook 302 0 - 16.254 ms
Error: field "name" not found in type: 'users': {"response":{"errors":[{"extensions":{"path":"$.selectionSet.auth_account_providers.selectionSet.account.selectionSet.accountFragment.selectionSet.user.selectionSet.name","code":"validation-failed"},"message":"field \"name\" not found in type: 'users'"}],"status":200},"request":{"query":"query ($provider: String!, $profile_id: String!) {\n  auth_account_providers(where: {_and: [{auth_provider: {_eq: $provider}}, {auth_provider_unique_id: {_eq: $profile_id}}]}) {\n    account {\n      ...accountFragment\n    }\n  }\n}\n\nfragment accountFragment on auth_accounts {\n  id\n  active\n  default_role\n  account_roles {\n    role\n  }\n  user {\n    id\n    display_name\n    name\n  }\n  is_anonymous\n  ticket\n  email\n  new_email\n  otp_secret\n  mfa_enabled\n  password_hash\n}\n","variables":{"provider":"facebook","profile_id":"5269377376421556"}}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/src/index.ts:72:13)
    at step (/app/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/app/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/app/node_modules/graphql-request/dist/src/index.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  response: { errors: [ [Object] ], status: 200 },
  request: {
    query: 'query ($provider: String!, $profile_id: String!) {\n' +
      '  auth_account_providers(where: {_and: [{auth_provider: {_eq: $provider}}, {auth_provider_unique_id: {_eq: $profile_id}}]}) {\n' +
      '    account {\n' +
      '      ...accountFragment\n' +
      '    }\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment accountFragment on auth_accounts {\n' +
      '  id\n' +
      '  active\n' +
      '  default_role\n' +
      '  account_roles {\n' +
      '    role\n' +
      '  }\n' +
      '  user {\n' +
      '    id\n' +
      '    display_name\n' +
      '    name\n' +
      '  }\n' +
      '  is_anonymous\n' +
      '  ticket\n' +
      '  email\n' +
      '  new_email\n' +
      '  otp_secret\n' +
      '  mfa_enabled\n' +
      '  password_hash\n' +
      '}\n',
    variables: { provider: 'facebook', profile_id: <MY PROFILE ID WAS HERE> }
  }
}
(node:34) UnhandledPromiseRejectionWarning: Error: Internal Server Error
    at Object.request (/app/src/shared/request.ts:29:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Strategy._verify (/app/src/routes/auth/providers/utils.ts:55:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:34) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SkinyMonkey** [comment]
From my understanding it's because i built a custom version of HBP+ to understand the way provider works and the JWT_CUSTOM_FIELDS were field by the local .env.ci

But it also mean that an a promise rejections wasnt handled, which i guess you don't want to have.
The handling could even tell a usefull message to the HBP+ user, like "Your JWT_CUSTOM FIELDS referenced a field that doesnt exist in your current schema : name"

**Comment by komninoschat** [comment]
See #426.
