### ISSUE TITLE
Can't Generate QR Code

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-backend-plus#406]
When I run `POST /auth/mfa/generate`, while logged into my SPA, I get the following error:

```json
{"statusCode":401,"error":"Unauthorized","message":"Not logged in"}
```

I've made the API request using the header: `{withCredentials: true}` and it had no effect.

I have gotten it to work on Postman but can't get it to work in the browser.

Here is the server log:

```
Error: Not logged in
    at generateMfa (/app/dist/routes/auth/mfa/generate.js:14:30)
    at /app/dist/shared/helpers.js:33:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
POST /auth/mfa/generate 401 67 - 1.750 ms
    at router (/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 401,
    payload: {
      statusCode: 401,
      error: 'Unauthorized',
      message: 'Not logged in'
    },
    headers: {}
  }
}
```

I'm currently making this request on a React app on `localhost:3001`. My guess is it could be related to CORS or I'm missing an environmental variable, but I couldn't find more information in the documentation.

**Comment by elitan** [comment]
Do you send the JWT token as an `Authorization` header or do you use cookies?

Can you double check the request bening made from your browser if it has either the `Authorization` header or the cookie?

**Comment by joshmedeski** [comment]
On Postman, I'm using cookies and it works fine.

I will use an authorization header and get back to you.

**Comment by joshmedeski** [comment]
Got this working by properly calling `withCredentials` in the header.
