### ISSUE TITLE
Unique value  for Registration Custom Fields

### ISSUE THREAD

**Issue by develogo** [nhost/hasura-backend-plus#426]
I created a column in users and called it id_doc and defined it as unique. Assigned this column at REGISTRATION CUSTOM FIELDS = id_doc, at the time of registering everything is fine. If I try to register an id_doc already present in the database, I have error 500, and it is not informed which value is wrong. There is a way for hbp to say that that value is unique and that it already exists, similar to what is done with email.

**Comment by komninoschat** [comment]
Resolve #471 and see if that fixes it.

**Comment by elitan** [comment]
HBP still returns 500 but the error logs are now better:

```
Error inserting user account
Error: Not-NULL violation. null value in column "doc_id" violates not-null constraint: {"response":{"errors":[{"extensions":{"path":"$.selectionSet.insert_auth_accounts.args.objects[0].user.data","code":"constraint-violation"},"message":"Not-NULL violation. null value in column \"doc_id\" violates not-null constraint"}],"status":200},"request":{"query":"mutation ($account: auth_accounts_insert_input!) {\n  insert_auth_accounts(objects: [$account]) {\n    affected_rows\n    returning {\n      ...accountFragment\n    }\n  }\n}\n\nfragment accountFragment on auth_accounts {\n  id\n  active\n  default_role\n  account_roles {\n    role\n  }\n  user {\n    id\n    display_name\n  }\n  is_anonymous\n  ticket\n  email\n  new_email\n  otp_secret\n  mfa_enabled\n  password_hash\n}\n","variables":{"account":{"email":"johan3@nhost.io","password_hash":"$2a$10$/WXGtRXm00IeP4O1MM3mMuygsF5JrxFG4pRBAOHwCMW5bg3EXM35i","ticket":"b9023557-49f7-4abc-bebd-2427f7e1242f","ticket_expires_at":"2021-07-14T14:34:07.443Z","active":true,"default_role":"user","account_roles":{"data":[{"role":"user"},{"role":"me"}]},"user":{"data":{"display_name":"johan3@nhost.io"}}}}}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/src/index.ts:72:13)
    at step (/app/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/app/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/app/node_modules/graphql-request/dist/src/index.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  response: { errors: [ [Object] ], status: 200 },
  request: {
    query: 'mutation ($account: auth_accounts_insert_input!) {\n' +
      '  insert_auth_accounts(objects: [$account]) {\n' +
      '    affected_rows\n' +
      '    returning {\n' +
      '      ...accountFragment\n' +
      '    }\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'fragment accountFragment on auth_accounts {\n' +
      '  id\n' +
      '  active\n' +
      '  default_role\n' +
      '  account_roles {\n' +
      '    role\n' +
      '  }\n' +
      '  user {\n' +
      '    id\n' +
      '    display_name\n' +
      '  }\n' +
      '  is_anonymous\n' +
      '  ticket\n' +
      '  email\n' +
      '  new_email\n' +
      '  otp_secret\n' +
      '  mfa_enabled\n' +
      '  password_hash\n' +
      '}\n',
    variables: { account: [Object] }
  }
}
```
