### ISSUE TITLE
Spotify Oauth Failing

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-backend-plus#619]
I'm getting the following error for Spotify oauth callback:

```
::1 - - [09/Jul/2021:15:20:55 +0000] "GET /auth/providers/spotify HTTP/1.1" 302 0
InternalOAuthError: failed to fetch user profile
    at /Users/joshmedeski/repos/hasura-backend-plus/node_modules/passport-spotify/lib/passport-spotify/strategy.js:151:19
    at passBackControl (/Users/joshmedeski/repos/hasura-backend-plus/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/joshmedeski/repos/hasura-backend-plus/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:387:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  oauthError: { statusCode: 403, data: 'Forbidden' }
}
```

According to [this issue](https://github.com/JMPerez/passport-spotify/issues/77) it could be an issue with the implementation of the Spotify Passport strategy.

I'm investigating and will come back with

**Comment by joshmedeski** [comment]
According to Spotify: 

> Submit a scope extension request
> If you’d like to add an OAuth scope to your app, and your app is in extended quota mode then you can let us know by creating a scope extension request.

I'll get this approved by Spotify and let you know if the issue is still there.
