### ISSUE TITLE
Error: field "user_accounts" not found in type: 'users_insert_input'

### ISSUE THREAD

**Issue by pnfcre** [nhost/hasura-backend-plus#93]
Hi there,

When sending a POST request to `/auth/local/register` to register a new user, as described in the README, I end up with the following error:

```
{ Error: field "user_accounts" not found in type: 'users_insert_input': {"response":{"errors":[{"extensions":{"path":"$.variableValues.user.user_accounts","code":"validation-failed"},"message":"field \"user_accounts\" not found in type: 'users_insert_input'"}],"status":200},"request":{"query":"\n  mutation (\n    $user: users_insert_input!\n  ) {\n    insert_users (\n      objects: [$user]\n    ) {\n      affected_rows\n    }\n  }\n  ","variables":{"user":{"display_name":"pnfcre","active":true,"secret_token":"768b2ea0-3a4e-4ed6-bec9-6bb08aa88770","user_accounts":{"data":{"username":"pnfcre","password":"$2a$10$YJhlxntg/sGwV8ntIK57wextVqZsru4FjEjClgqkTJ6Dev4DK1Jzm"}}}}}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/src/index.js:116:35)
    at step (/app/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/app/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/app/node_modules/graphql-request/dist/src/index.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response: { errors: [ [Object] ], status: 200 },
  request:
   { query:
      '\n  mutation (\n    $user: users_insert_input!\n  ) {\n    insert_users (\n      objects: [$user]\n    ) {\n      affected_rows\n    }\n  }\n  ',
     variables: { user: [Object] } } }
Unable to create user.
Error: Unable to create user.
    at router.post (/app/src/auth/local.js:74:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
POST /auth/local/register 500 96 - 221.425 ms
```

I followed the instructions, so I'm not sure what I did wrong.

Thanks for any help!

Kind regards,
Hampus Kraft.

**Comment by pnfcre** [comment]
Nevermind, I solved it by tracking all tables in the `auth` schema! 👍
